//head file

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Head from "next/head";

//components
import Navbar from "./components/Navbar";
import AboutUs from "./aboutus/page";
import DonateUs from "./donateus/page";
import Footer from "./footer/page";
import KnowGod from "./knowgod/page";
import ScrollButton from "./components/ScrollButton";

export const metadata = {
  title: "Full Life AG Church",
  description: "Generated by create next app"
};
// export const viewport = {
//   initialScale: 1,
//   width: 'device-width'
// }
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta
          name="viewport"
          content="width=device-width; initial-scale=1; shrink-to-fit=no"
        />
      </head>
      <body>
        <Navbar />
        <div className="div">
          <Image
            src="/Images/familyPic.jpg"
            alt="Descriptive alt text"
            width={1920}
            height={1080}
            className="mobile-only-family-image"
          />
          {children}
        </div>
        <AboutUs />
        <KnowGod />
        <DonateUs />
        <Footer />
        <ScrollButton />
      </body>
    </html>
  );
}
