import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Head from "next/head";

//components
import Navbar from "./components/Navbar";
import AboutUs from "./aboutus/page"
import DonateUs from "./donateus/page";
import Footer from "./footer/page";
import KnowGod from "./knowgod/page";
import ScrollButton from "./components/ScrollButton";

export const metadata = {
  title: "Full Life AG Church",
  description: "Generated by create next app"
};
// export const viewport = {
//   initialScale: 1,
//   width: 'device-width'
// }
export default function RootLayout({ children }) {
  return (
    <html lang="en">
     {/* <Head> */}
     <meta name="viewport" content="width=device-width, initial-scale=0.1" />
     {/* </Head> */}
      <body className="body">
        <div className="">
        <div className="div">
        <Navbar />
        </div>
        {children}
        <AboutUs/>
        <KnowGod />
        <DonateUs />
        <Footer />
        <ScrollButton />
        </div>
      </body>
    </html>
  );
}
