const seniorPastorDetails = [ 
"Rev. N. Johnson’s life is a powerful testimony of God’s grace and transformation. Born and raised in a Hindu family in a small village in India, young Johnson had an intense longing to see and know God—even at the age of 13. He spent hours in a local library, reading Hindu legends in search of divine truth. However, the more he read, the more he realized that these stories were mere myths, leading him to question his beliefs.",
"Disillusioned, he turned to atheism and drifted into a life of sin. Yet, despite his attempts to find satisfaction, his heart remained empty, and his mind was tormented by fear of the future. It was during this season of searching that a family friend invited him to a Christmas service in a nearby town. Though hesitant, Johnson attended—and that decision changed his life forever. That day, the Lord touched him, transformed his heart, and filled him with His peace. On September 3, 1989, Johnson accepted Jesus Christ as his Savior and was baptized.",
"He later began working as a machine operator at a granite company. One evening, as he was praying, he had a divine encounter. The Lord spoke to him, saying, 'You have only one life, and it passes away like a tale that is told. Spend it in My service, and I will give you an eternal crown.' Overwhelmed by God’s call, Johnson surrendered his life to ministry, resigning from his job to pursue theological studies. In 1994, he joined Southern Asia Bible College in Bangalore and, in 1997, graduated with a Bachelor of Theology degree. He then served under Rev. Jaipal (Living Gospel Fellowship, Bangalore) and Rev. John Jebaraj (Praise Assembly, Chennai), gaining valuable ministry experience.",
"In 1998, Johnson married Jemimah, and soon after, they moved to Thiruverkadu to pioneer a church. Through their unwavering faith and commitment, God blessed their ministry abundantly. Their family also grew, with the birth of their son, Jerry Jemson, and daughter, Jerusha Pearlin.",
"Today, Rev. N. Johnson holds a Master’s in Theology and is pursuing his Doctorate. God is using him mightily, and his life and ministry continue to impact and bless countless people in Thiruverkadu and beyond. His story stands as a testament to the faithfulness of God and the power of a life fully surrendered to His call." 
]

export default seniorPastorDetails;
